### ISSUE TITLE
Add support for secretReference with harness_encrypted_text resource

### ISSUE THREAD

**Issue by matthewmedway** [harness-io/terraform-provider-harness#37]
Would like to see this added as an option.
GraphQL api supports this:
```
mutation($secret: CreateSecretInput!){
  createSecret(input: $secret){
    secret{
      id,
      name
      ... on EncryptedText{
        name
        secretManagerId
        id
      }
      usageScope{
        appEnvScopes{
          application{
            filterType
            appId
          }
          environment{
            filterType
            envId
          }
        }
      }
    }
  }
}
```
Variables:
```
"secret": {
      "secretType": "ENCRYPTED_TEXT",
      "encryptedText": {
        "name": secret_name,
        "secretReference": secret_reference_name,
        "secretManagerId": secret_manager_id,
        "usageScope": {
          "appEnvScopes": [{
            "application": {
              "filterType": "ALL"
            },
            "environment": {
              "filterType": "PRODUCTION_ENVIRONMENTS"
            }
          }]
        }
      }
    }
  }
```

**Comment by micahlmartin** [comment]
Hi @matthewmedway thanks for the submission. I haven't yet seen this functionality. Can you help me understand the use case for this?

**Comment by matthewmedway** [comment]
It's used to create a Harness encrypted text Secret that is a reference to an already existing secret in AWS Secrets Manager or HashiCorp Vault or other secrets service:
https://docs.harness.io/article/cwp7rlauzn-reference-existing-secrets

**Comment by micahlmartin** [comment]
@matthewmedway ah nice. Yeah I can get that added for sure.

**Comment by micahlmartin** [comment]
@matthewmedway unfortunately there's a gap in the API response. I can't get the referenced secret field back when querying for the newly created secret. It's missing as a field in the object response which means Terraform will always think there is a change. I've filed a bug with the team to get this ironed out. In the meantime, I can implement this but you would have to set `lifecycle { ignore_changes = ["secret_reference"] }` on any secrets you create until this is fixed. Let me know if that's good for you.

**Comment by micahlmartin** [comment]
@matthewmedway actually you wont need the `ignore_changes` flag, but if someone updates the reference in the UI or you import the resource into terraform the `secret_reference` field will not be updated.
