### ISSUE TITLE
harness_environment variable_override bug

### ISSUE THREAD

**Issue by brianbuda** [harness-io/terraform-provider-harness#56]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
1.0.0

### Affected Resource(s)
Please list the resources as a list, for example:
- harness_environment

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "harness_environment" "test" {
  app_id = "Harness Application"
  name   = "Test"
  type   = "NON_PROD"

  variable_override {
    name         = "test"
    value        = "override"
    type         = "TEXT"
  }
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
Create a variable override for all services instead of defining on one service.

### Actual Behavior
What actually happened?
When running the terraform plan, receive the error of:

The argument "service_name" is required, but no definition was found.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by micahlmartin** [comment]
Hi @brianbuda . Can you provide any details as to what error you're experiencing?

**Comment by brianbuda** [comment]
The service ID is required but when you look at the yaml file for one of
"All Services", there is no I'd, that key doesn't exist. It seems if you
make that parameter optional, that will fix the issue.

Brian

**Comment by stan-yago** [comment]
@brianbuda In resource "harness_environment" app_id is not the name of the app, but the id harness assigned internally

To get the id of existing app you can use something like
```
   data "harness_application" "my_app" {
     name = "Harness Application"
   }
```

and then you can
```
resource "harness_environment" "test" {
  app_id = data.my_app.id
```

**Comment by brianbuda** [comment]
@stan-yago you're correct, that's a typo in my Configuration File, but the issue is wanting to have a variable_override for "All Services" like you can do from the UI.  Currently with the harness_environment, the service_name is required for the variable_override

**Comment by MrFishFinger** [comment]
@brianbuda  - as a workaround, you should be able to specify an empty string for `service_name`, to create an "All Service" Variable Override. For example:

```
  variable_override {
    service_name = ""
    name         = "env_name"
    value        = "prod"
    type         = "TEXT"
  }
```

**Comment by micahlmartin** [comment]
Fixed by https://github.com/harness-io/terraform-provider-harness/commit/beaeb790bdcff96fe4e110faa50b0b103d4fb18a
