### ISSUE TITLE
Delegate Data source - Be able to get all delegates in a condition

### ISSUE THREAD

**Issue by diegopereiraeng** [harness-io/terraform-provider-harness#61]
### Expected Behavior
What should have happened?

Be able to get all delegates running in kubernetes that are enabled!

`data "harness_delegate" "example" {`
`  type   = "KUBERNETES"`
`  status = "ENABLED"`
`}`

### Actual Behavior
What actually happened?

name is required, so it is not possible!

**Comment by micahlmartin** [comment]
closed by https://github.com/harness-io/terraform-provider-harness/commit/d03b836d22751dbb83529bef524503a6f63454d0
